/**
 * Fallback country resolver for leads whose customer has no `country` set —
 * the common case, since neither the manual "New Enquiry" form nor the
 * website lead webhook currently capture one. Most pickup/destination text
 * on a lead is just a bare city, airport or district name ("Dubai",
 * "Sharjah", "Manchester"), so a city -> ISO country lookup recovers a
 * usable country for the dashboard map in the large majority of cases.
 * Not exhaustive — unresolvable text is simply skipped by the caller.
 */
const CITY_TO_COUNTRY: Record<string, string> = {
  dubai: "AE",
  "abu dhabi": "AE",
  sharjah: "AE",
  ajman: "AE",
  "ras al khaimah": "AE",
  fujairah: "AE",
  "umm al quwain": "AE",
  "al ain": "AE",
  riyadh: "SA",
  jeddah: "SA",
  dammam: "SA",
  mecca: "SA",
  makkah: "SA",
  medina: "SA",
  doha: "QA",
  "kuwait city": "KW",
  manama: "BH",
  muscat: "OM",
  salalah: "OM",
  amman: "JO",
  petra: "JO",
  beirut: "LB",
  cairo: "EG",
  alexandria: "EG",
  giza: "EG",
  "sharm el sheikh": "EG",
  hurghada: "EG",
  baghdad: "IQ",
  tehran: "IR",
  "tel aviv": "IL",
  jerusalem: "IL",
  damascus: "SY",
  sanaa: "YE",
  london: "GB",
  manchester: "GB",
  birmingham: "GB",
  liverpool: "GB",
  edinburgh: "GB",
  glasgow: "GB",
  leeds: "GB",
  bristol: "GB",
  dublin: "IE",
  paris: "FR",
  nice: "FR",
  lyon: "FR",
  marseille: "FR",
  cannes: "FR",
  berlin: "DE",
  munich: "DE",
  frankfurt: "DE",
  hamburg: "DE",
  cologne: "DE",
  madrid: "ES",
  barcelona: "ES",
  seville: "ES",
  ibiza: "ES",
  rome: "IT",
  milan: "IT",
  venice: "IT",
  florence: "IT",
  naples: "IT",
  amsterdam: "NL",
  rotterdam: "NL",
  brussels: "BE",
  zurich: "CH",
  geneva: "CH",
  vienna: "AT",
  lisbon: "PT",
  porto: "PT",
  copenhagen: "DK",
  stockholm: "SE",
  oslo: "NO",
  helsinki: "FI",
  reykjavik: "IS",
  warsaw: "PL",
  krakow: "PL",
  prague: "CZ",
  budapest: "HU",
  bucharest: "RO",
  athens: "GR",
  santorini: "GR",
  mykonos: "GR",
  zagreb: "HR",
  dubrovnik: "HR",
  istanbul: "TR",
  ankara: "TR",
  antalya: "TR",
  moscow: "RU",
  "st petersburg": "RU",
  kyiv: "UA",
  "new york": "US",
  "los angeles": "US",
  chicago: "US",
  miami: "US",
  "las vegas": "US",
  "san francisco": "US",
  boston: "US",
  washington: "US",
  seattle: "US",
  orlando: "US",
  houston: "US",
  dallas: "US",
  atlanta: "US",
  toronto: "CA",
  vancouver: "CA",
  montreal: "CA",
  "mexico city": "MX",
  cancun: "MX",
  "sao paulo": "BR",
  "rio de janeiro": "BR",
  "buenos aires": "AR",
  santiago: "CL",
  bogota: "CO",
  lima: "PE",
  delhi: "IN",
  "new delhi": "IN",
  mumbai: "IN",
  bangalore: "IN",
  bengaluru: "IN",
  chennai: "IN",
  hyderabad: "IN",
  kolkata: "IN",
  goa: "IN",
  jaipur: "IN",
  pune: "IN",
  karachi: "PK",
  lahore: "PK",
  islamabad: "PK",
  dhaka: "BD",
  colombo: "LK",
  kathmandu: "NP",
  beijing: "CN",
  shanghai: "CN",
  "hong kong": "HK",
  shenzhen: "CN",
  guangzhou: "CN",
  macau: "HK",
  tokyo: "JP",
  osaka: "JP",
  kyoto: "JP",
  seoul: "KR",
  taipei: "TW",
  bangkok: "TH",
  phuket: "TH",
  "chiang mai": "TH",
  singapore: "SG",
  "kuala lumpur": "MY",
  penang: "MY",
  jakarta: "ID",
  bali: "ID",
  manila: "PH",
  cebu: "PH",
  "ho chi minh city": "VN",
  hanoi: "VN",
  sydney: "AU",
  melbourne: "AU",
  brisbane: "AU",
  perth: "AU",
  auckland: "NZ",
  johannesburg: "ZA",
  "cape town": "ZA",
  durban: "ZA",
  nairobi: "KE",
  lagos: "NG",
  abuja: "NG",
  accra: "GH",
  casablanca: "MA",
  marrakech: "MA",
  tunis: "TN",
  algiers: "DZ",
};

const CITY_KEYS_BY_LENGTH_DESC = Object.keys(CITY_TO_COUNTRY).sort((a, b) => b.length - a.length);

/** Best-effort ISO alpha-2 country code for a free-text place name/address. */
export function resolveCityCountryCode(rawText: string | null | undefined): string | null {
  if (!rawText) return null;
  const normalized = rawText.trim().toLowerCase();
  if (!normalized) return null;

  if (CITY_TO_COUNTRY[normalized]) return CITY_TO_COUNTRY[normalized];

  // Fall back to substring match for richer strings ("Dubai Marina",
  // "Dubai International Airport, Terminal 3"). Longest names first so
  // "abu dhabi" wins over any shorter accidental overlap.
  for (const city of CITY_KEYS_BY_LENGTH_DESC) {
    if (normalized.includes(city)) return CITY_TO_COUNTRY[city]!;
  }
  return null;
}
